name: Render vignette as README.md

on:
  workflow_dispatch:
  push:
    paths:
    - vignettes/AnVILPublishIntro.Rmd

jobs:
  render:
    name: Render README
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
          Ncpus: '4'
          crayon.enabled: 'FALSE'
      - uses: r-lib/actions/setup-pandoc@v1
      - name: install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install rmarkdown, remotes, and the local package
        run: |
          options(repos = c(
              "https://packagemanager.rstudio.com/all/__linux__/focal/latest",
              CRAN = "https://cran.r-project.org"
          ))
          install.packages(c("remotes", "BiocManager"))
          BiocManager::install(version = "devel", ask = FALSE)
          BiocManager::install(c("Bioconductor/AnVIL", "rmarkdown"))
          remotes::install_local(".")
        shell: Rscript {0}
      - name: Render vignette
        run: |
          rmarkdown::render(
              "vignettes/AnVILPublishIntro.Rmd",
              output_file = "../README.md",
              rmarkdown::md_document()
          )
        shell: Rscript {0}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md -m 'Re-build vignettes/AnVILPublishIntro.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"